// AUTO-GENERATED by scripts/measure-real-sample.ts — do not edit by hand.
// Measured facts about the real public/samples/sample_dieline.pdf (provided
// by the user), computed by running it through the actual src/core pipeline
// (extract -> classify -> panels -> graph -> solver -> audit).
//
// segmentCounts is the WORKING, post-flatten count (every cubic Bezier
// flattened to short straight pieces at the 0.05mm chord tolerance in
// bezier.ts) — this is what classify/panels/solver actually operate on.
// rawCounts.straight is an exact 1:1 count of lineTo operators in the PDF
// content stream (76). rawCounts.curve is NOT a count of
// curveTo operators (there are 12 of those, matching the brief's "12 cubic
// Bezier") — it's how many short straight pieces those 12 curves flatten
// into at the 0.05mm chord tolerance in bezier.ts (116).

export const SAMPLE_EXPECTATIONS = {
  segmentCounts: {"total":192,"cut":174,"crease":17,"perf":1},
  rawCounts: {"straight":76,"curve":116},
  panelCount: 16,
  dims: { L: 154, H: 95, D: 16.5 }
} as const;
