// Measures the REAL sample_dieline.pdf (provided by the user, copied into
// public/samples/) by running it through the real src/core pipeline, and
// writes src/core/sampleExpectations.ts as a locked-in regression baseline.
//
// Uses pdf.js's Node build directly for getDocument/getOperatorList, then
// hands the operator list to the SAME walkPdfOperatorList used by the real
// browser extractor (src/core/extract/pdf.ts) — no duplicated CTM/colour
// logic. Everything downstream (classify, panels, graph, solver, audit)
// imports the real src/core modules too, so this script is the single
// source of truth for "what does the real file measure".
//
// Run with: node --experimental-strip-types scripts/measure-real-sample.ts

import { writeFileSync, readFileSync } from 'node:fs';
import * as pdfjsLib from '../node_modules/pdfjs-dist/build/pdf.mjs';
import { walkPdfOperatorList } from '../src/core/extract/pdfOperatorWalk.ts';
import { classifySegments } from '../src/core/classify.ts';
import { decomposePanels } from '../src/core/panels.ts';
import { solveFoldSchedule } from '../src/core/solver.ts';
import { computeAudit } from '../src/core/audit.ts';

async function extractRealPdf(path: string) {
  const data = new Uint8Array(readFileSync(path));
  const doc = await pdfjsLib.getDocument({ data, isEvalSupported: false }).promise;
  const page = await doc.getPage(1);
  const opList = await page.getOperatorList();
  return walkPdfOperatorList(opList, pdfjsLib.OPS);
}

function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

(async () => {
  const { raw, rawCounts } = await extractRealPdf('public/samples/sample_dieline.pdf');
  const classified = classifySegments(raw);
  const { panels } = decomposePanels(classified.segments);
  const schedule = solveFoldSchedule({
    panels,
    segments: classified.segments,
    classificationStrategy: classified.strategy
  });
  const audit = computeAudit(schedule, null);

  console.log('--- Real sample_dieline.pdf measurement ---');
  console.log('Classification strategy:', classified.strategy);
  console.log('Raw counts (pre-flatten):', rawCounts);
  console.log('Working segment counts (post-flatten):', audit.segmentCounts);
  console.log('Panels:', panels.length);
  console.log('Dims:', schedule.dims);
  console.log('Perimeter identity:', schedule.perimeterIdentity);
  console.log('Closure residual (mm):', audit.closureResidualMm);
  console.log('Isometry drift (max):', audit.isometryDriftMax);
  console.log('Orphan panels:', schedule.orphanPanels);

  if (panels.length < 10) throw new Error('Panel count implausibly low — extraction likely broken');
  if (!schedule.perimeterIdentity?.holds) throw new Error('Perimeter identity does not hold');
  if (schedule.orphanPanels.length > 0) throw new Error('Fold graph is not connected');
  if (audit.isometryDriftMax === null || !audit.isometryPass) {
    throw new Error(`Isometry drift check failed: ${audit.isometryDriftMax}`);
  }

  const expectationsSource = `// AUTO-GENERATED by scripts/measure-real-sample.ts — do not edit by hand.
// Measured facts about the real public/samples/sample_dieline.pdf (provided
// by the user), computed by running it through the actual src/core pipeline
// (extract -> classify -> panels -> graph -> solver -> audit).
//
// segmentCounts is the WORKING, post-flatten count (every cubic Bezier
// flattened to short straight pieces at the 0.05mm chord tolerance in
// bezier.ts) — this is what classify/panels/solver actually operate on.
// rawCounts.straight is an exact 1:1 count of lineTo operators in the PDF
// content stream (${rawCounts.straight}). rawCounts.curve is NOT a count of
// curveTo operators (there are 12 of those, matching the brief's "12 cubic
// Bezier") — it's how many short straight pieces those 12 curves flatten
// into at the 0.05mm chord tolerance in bezier.ts (${rawCounts.curve}).

export const SAMPLE_EXPECTATIONS = {
  segmentCounts: ${JSON.stringify(audit.segmentCounts)},
  rawCounts: ${JSON.stringify(rawCounts)},
  panelCount: ${panels.length},
  dims: { L: ${round(schedule.dims.L)}, H: ${round(schedule.dims.H)}, D: ${round(schedule.dims.D)} }
} as const;
`;

  writeFileSync('src/core/sampleExpectations.ts', expectationsSource);
  console.log('\nWrote src/core/sampleExpectations.ts');
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
